### PR TITLE
Order generated use statements

### PR DESCRIPTION
**Pull request by enumag**
Currently the use statements are not ordered and my other tools (IDE settings, coding style fixer etc.) don't like that.

### CODE REVIEW

**Comment by enumag** [comment]
Build failing on hhvm. It's not related to my change.

**Comment by enumag** [comment]
@mcg-web Can I ask for a stable release?

**Comment by mcg-web** [comment]
done @enumag https://github.com/overblog/GraphQLPhpGenerator/releases/tag/v0.7.5 ! Thanks again!

**Comment by enumag** [comment]
Thank you!

**Pull request merged**
